const PUBLISH_STATUS = ['ACTIVE', 'INACTIVE'];
const PRODUCT_STATUS = ['DRAFT', 'ACTIVE', 'INACTIVE', 'ARCHIVED'];
const USER_TYPES = ['ADMIN', 'CUSTOMER'];
const USER_STATUS = ['ACTIVE', 'INACTIVE', 'SUSPENDED'];
const DISCOUNT_TYPES = ['PERCENTAGE', 'FIXED'];

const ORDER_STATUS = ['PENDING', 'PAID', 'PROCESSING', 'SENT', 'DELIVERED', 'CANCELLED', 'REFUNDED'];
// Allowed transitions. CANCELLED and REFUNDED are terminal.
const ORDER_TRANSITIONS = Object.freeze({
  PENDING: ['PAID', 'CANCELLED'],
  PAID: ['PROCESSING', 'SENT', 'CANCELLED', 'REFUNDED'],
  PROCESSING: ['SENT', 'CANCELLED', 'REFUNDED'],
  SENT: ['DELIVERED', 'REFUNDED'],
  DELIVERED: ['REFUNDED'],
  CANCELLED: [],
  REFUNDED: [],
});
const PAYMENT_STATUS = ['PENDING', 'AUTHORIZED', 'PAID', 'FAILED', 'REFUNDED', 'PARTIALLY_REFUNDED'];
const REVENUE_ORDER_STATUSES = ['PAID', 'PROCESSING', 'SENT', 'DELIVERED'];
const VOUCHER_ISSUABLE_ORDER_STATUSES = ['PAID', 'PROCESSING', 'SENT', 'DELIVERED'];

const VOUCHER_STATUS = ['ACTIVE', 'REDEEMED', 'EXPIRED', 'EXCHANGED', 'CANCELLED'];
const VOUCHER_TRANSITIONS = Object.freeze({
  ACTIVE: ['REDEEMED', 'EXPIRED', 'EXCHANGED', 'CANCELLED'],
  REDEEMED: [],
  EXPIRED: ['ACTIVE'], // reinstatement (goodwill) - requires a new future expiryDate
  EXCHANGED: [],
  CANCELLED: [],
});

const BLOG_STATUS = ['DRAFT', 'PUBLISHED', 'ARCHIVED'];
const REVIEW_STATUS = ['PENDING', 'APPROVED', 'REJECTED'];
const ITEM_TYPES = ['PRODUCT', 'GIFT_BOX'];
const BANNER_PLACEMENTS = ['HOME_HERO', 'HOME_SECONDARY', 'CATEGORY'];
const BANNER_TEXT_POSITIONS = ['LEFT', 'CENTER', 'RIGHT'];
const BANNER_TEXT_THEMES = ['DARK', 'LIGHT'];

module.exports = {
  PUBLISH_STATUS, PRODUCT_STATUS, USER_TYPES, USER_STATUS, DISCOUNT_TYPES,
  ORDER_STATUS, ORDER_TRANSITIONS, PAYMENT_STATUS, REVENUE_ORDER_STATUSES, VOUCHER_ISSUABLE_ORDER_STATUSES,
  VOUCHER_STATUS, VOUCHER_TRANSITIONS, BLOG_STATUS, REVIEW_STATUS, ITEM_TYPES,
  BANNER_PLACEMENTS, BANNER_TEXT_POSITIONS, BANNER_TEXT_THEMES,
};
