module.exports = {
  User: require('./User'),
  Role: require('./Role'),
  Category: require('./Category'),
  Partner: require('./Partner'),
  Product: require('./Product'),
  GiftBox: require('./GiftBox'),
  Coupon: require('./Coupon'),
  Order: require('./Order'),
  OrderItem: require('./OrderItem'),
  Voucher: require('./Voucher'),
  Payment: require('./Payment'),
  Banner: require('./Banner'),
  CuratedCollection: require('./Collection'),
  Blog: require('./Blog'),
  Faq: require('./Faq'),
  Cart: require('./Cart'),
  Wishlist: require('./Wishlist'),
  Review: require('./Review'),
  Setting: require('./Setting'),
  RefreshToken: require('./RefreshToken'),
  AuditLog: require('./AuditLog'),
};
